import{a as m,S as f,i as l}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h="50290691-d51719558e36c91c48babc26d",y="https://pixabay.com/api/";function b(n){console.log("Виклик функції getImagesByQuery із запитом:",n);const r={key:h,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return console.log("Параметри запиту сформовані:",r),m.get(y,{params:r}).then(o=>o.data).catch(o=>{throw o})}const a=document.querySelector(".gallery");console.log("Контейнер галереї знайдено:",a);let c=null;function L(n){const r=n.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:i,comments:p,downloads:d})=>(console.log("Обробка зображення:",{webformatURL:o,largeImageURL:s,tags:e}),`
          <li class="gallery-item">
            <a href="${s}" class="gallery-link">
            <img src="${o}" alt="${e}" loading="lazy" />
            </a>
          <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${p}</p>
          <p><b>Downloads:</b> ${d}</p>
        </div>
      </li>`)).join("");a.insertAdjacentHTML("beforeend",r),c?c.refresh():(c=new f(".gallery a",{captionsData:"alt",captionDelay:250}),console.log("Створено новий екземпляр SimpleLightbox:",c))}function v(){a.innerHTML=""}function O(){document.body.classList.add("loading")}function S(){document.body.classList.remove("loading")}const g=document.querySelector(".form"),u=g.querySelector('input[name="search-text"]');console.log("main.js завантажено.");document.addEventListener("DOMContentLoaded",()=>{console.log("DOMContentLoaded: DOM повністю завантажений.")});g.addEventListener("submit",n=>{n.preventDefault(),console.log("Форма відправлена.");const r=u.value.trim();if(console.log("Пошуковий запит:",r),!r){l.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"}),console.log("Пошуковий запит порожній.");return}v(),O(),b(r).then(o=>{if(console.log("Після виклику getImagesByQuery. Отримано дані:",o),!o.hits||o.hits.length===0){l.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),console.log("Масив hits порожній або не існує.");return}L(o.hits),console.log("Галерея створена. Кількість зображень:",o.hits.length),l.success({title:"Успіх",message:`Знайдено ${o.hits.length} зображень.`,position:"topRight",timeout:3e3})}).catch(o=>{l.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"}),console.error(o)}).finally(()=>{S(),u.value="",console.log("Лоадер схований, поле введення очищене.")})});
//# sourceMappingURL=index.js.map
