import{a as m,S as f,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const y="50290691-d51719558e36c91c48babc26d",h="https://pixabay.com/api/";async function b(s){const r={key:y,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};try{return(await m.get(h,{params:r})).data}catch(t){throw t}}const u=document.querySelector(".gallery");let l=null;function L(s){const r=s.map(({webformatURL:t,largeImageURL:i,tags:e,likes:o,views:n,comments:g,downloads:p})=>`
      <li class="gallery-item">
        <a href="${i}" class="gallery-link">
          <img src="${t}" alt="${e}" loading="lazy" />
        </a>
           <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${p}</p>
        </div>
  
      </li>`).join("");u.insertAdjacentHTML("beforeend",r),l?l.refresh():l=new f(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){u.innerHTML=""}function O(){document.body.classList.add("loading")}function w(){document.body.classList.remove("loading")}console.log("ghhjj");const d=document.querySelector(".form"),c=d.querySelector('input[name="search-text"]');console.log("main.js завантажено.");document.addEventListener("DOMContentLoaded",()=>{console.log("DOMContentLoaded: DOM повністю завантажений.")});d.addEventListener("submit",async s=>{s.preventDefault(),console.log("Форма відправлена.");const r=c.value.trim();if(console.log("Пошуковий запит:",r),!r){a.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"}),console.log("Пошуковий запит порожній.");return}v(),O();try{console.log("Перед викликом getImagesByQuery з запитом:",r);const t=await b(r);if(console.log("Після виклику getImagesByQuery. Отримано дані:",t),!t.hits||t.hits.length===0){a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),console.log("Масив hits порожній або не існує.");return}L(t.hits),console.log("Галерея створена. Кількість зображень:",t.hits.length),a.success({title:"Успіх",message:`Знайдено ${t.hits.length} зображень.`,position:"topRight",timeout:3e3})}catch(t){a.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"}),console.error(t)}finally{w(),c.value="",console.log("Лоадер схований, поле введення очищене.")}});
//# sourceMappingURL=index.js.map
