import{a as m,S as h,i as a}from"./assets/vendor-1AYLTIiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const g="50290691-d51719558e36c91c48babc26d",y="https://pixabay.com/api/";function b(i){const r={key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return m.get(y,{params:r}).then(t=>t.data).catch(t=>{throw t})}const u=document.querySelector(".gallery");let c=null;function L(i){const r=i.map(({webformatURL:t,largeImageURL:n,tags:e,likes:o,views:s,comments:p,downloads:f})=>(console.log("Обробка зображення:",{webformatURL:t,largeImageURL:n,tags:e}),`
          <li class="gallery-item">
            <a href="${n}" class="gallery-link">
            <img src="${t}" alt="${e}" loading="lazy" />
            </a>
          <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${p}</p>
          <p><b>Downloads:</b> ${f}</p>
        </div>
      </li>`)).join("");u.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new h(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){u.innerHTML=""}function S(){document.body.classList.add("loading")}function $(){document.body.classList.remove("loading")}const d=document.querySelector(".form"),l=d.querySelector('input[name="search-text"]');document.addEventListener("DOMContentLoaded",()=>{});d.addEventListener("submit",i=>{i.preventDefault();const r=l.value.trim();if(!r){a.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}v(),S(),b(r).then(t=>{if(!t.hits||t.hits.length===0){a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t.hits),a.success({title:"Успіх",message:`Знайдено ${t.hits.length} зображень.`,position:"topRight",timeout:3e3})}).catch(t=>{a.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"})}).finally(()=>{$(),l.value=""})});
//# sourceMappingURL=index.js.map
